#!/usr/bin/env bash

# The bash script used to transfer a file from our client to the server :
# we have some requirments:
#
#+  1-The path to the file to be transferred
#+  2-The IP of the server we want to transfer the file to
#+  3-The username scp connects with
#+  4-The path to the SSH private key that scp use

# By: Mohammed Farahat


if [ "$#" -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"

if [ $? -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
fi

