#!/usr/bin/env bash

# The bash script used to transfer a file from our client to the server :
# we have some requirments:
#
#+  1-The path to the file to be transferred
#+  2-The IP of the server we want to transfer the file to
#+  3-The username scp connects with
#+  4-The path to the SSH private key that scp use

# By: Mohammed Farahat

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
