#!/usr/bin/env bash
#1. Install nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
