#!/bin/bash

# Update package list and install nginx
#Create a simple HTML page
# Restart nginx without using systemctl
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx restart
